### ISSUE TITLE
Not able to change the font.

### ISSUE THREAD

**Issue by karthikeyaGit61** [wfpena/angular-wysiwyg#26]
Hello,

My current version is angular 16.2.13, and it is not letting me change the font.

**Comment by karthikeyaGit61** [comment]
@wfpena 

Surprisingly, it works now but only when clicked repeatedly, like 3 to 4 times. After that, "<br></font></div><font size="4" face="Comic Sans MS">Test 1</font>" seems to be changing.

However, single click never works. There are no errors in the console, by the way.

**Comment by wfpena** [comment]
@karthikeyaGit61 What do you mean exactly by single click?

Looks like it might be a bug. I'll try to reproduce it here, but if you have some steps to help reproduce it would be very much appreciated also.

**Comment by karthikeyaGit61** [comment]
@wfpena 

While changing the font by clicking on the dropdown item, it doesn't work on a single click. I had to click repeatedly for it to work.

I followed the right steps while installing. All the other buttons are working properly, but only the font seems to be the problem.
