### ISSUE TITLE
The icon and font does not appear when I am not connected to the Internet

### ISSUE THREAD

**Issue by yingchy1996** [wfpena/angular-wysiwyg#30]
My project is an intranet project and cannot access the external network. As a result, my font icons are not displayed. 

![Screenshot 2024 July 23 11-01](https://github.com/user-attachments/assets/a7153cd1-00cb-4914-8c28-a3c7265ad84d)

**Comment by yingchy1996** [comment]
Can fonts and graphics be deployed in the project?

**Comment by wfpena** [comment]
@yingchy1996 you can change the icons. On the README now has a section for a workaround to change the icons:

Take a look in there please on the **Changing the Icons** section

**Comment by yingchy1996** [comment]
I know，Thanks

**Comment by wfpena** [comment]
@yingchy1996  the new version 1.1.6 should solve the font problem https://github.com/wfpena/angular-wysiwyg/pull/31
