### ISSUE TITLE
I want to use innerHtml, but the centered style won't display. What should I do

### ISSUE THREAD

**Issue by yingchy1996** [wfpena/angular-wysiwyg#37]
![46b325d081ccaafcf476152d1d11d920](https://github.com/user-attachments/assets/75e23b9a-e6ac-41f5-93a6-f3be4d41cd67)

**Comment by yingchy1996** [comment]
I hope the style of formValue is the same as the value of outterHTML

**Comment by yingchy1996** [comment]
This will cause the styles in my innerHtml to be inconsistent with those in the editor

**Comment by yingchy1996** [comment]
For example, if I want to center, I use formValue and then innerHtml to display errors

**Comment by wfpena** [comment]
@yingchy1996 you should set the config value: 

`sanitize: false,`

To keep the inline styles.

**Comment by yingchy1996** [comment]
> @yingchy1996 you should set the config value:
> 
> `sanitize: false,`
> 
> To keep the inline styles.

Oh，it works，but i used other rich-editor last，thanks！
