### ISSUE TITLE
How to add new fontsizes?

### ISSUE THREAD

**Issue by Rop1ck** [wfpena/angular-wysiwyg#39]
I forked this project and tried to add some more fontsizes. This is what i currently achieved, but everytime i press anything larger than 7, it automatically changes it back to 7.
![Screenshot 2024-11-20 120320](https://github.com/user-attachments/assets/3f6a038f-511f-4e39-90d5-875a9ea32655)
Can you perhaps explain how to add more than 7 fontsizes?

**Comment by nicowolf91** [comment]
I guess that's not possible without having major changes to the lib, since it uses [execCommand](https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand#fontsize) to set the font size.
Therefore, font sizes can only be 1 to 7.

**Comment by Rop1ck** [comment]
Ahh ok thanks for the information 👍 And i thought what am i doing wrong :D

**Comment by wfpena** [comment]
Closing this based on @nicowolf91  's comment
